name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, macOS, MYRUNNER]
    steps:
      - uses: actions/checkout@v5
        with:
          clean: true

      - name: Install FVM Flutter SDK (.fvmrc)
        run: fvm install

      - name: Bootstrap, analyze, test
        run: make check
