name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
        working-directory: .
      - run: dart analyze packages/mac_dev_cleaner_core apps/mac-dev-cleaner-cli
      - run: dart test
        working-directory: packages/mac_dev_cleaner_core
